use crate::appicon;
use crate::db;
use crate::AppState;
use base64::Engine;
use clipboard_rs::common::RustImage;
use clipboard_rs::{Clipboard, ClipboardContext, ClipboardHandler, ClipboardWatcher, ClipboardWatcherContext, ContentFormat};
use sha2::{Digest, Sha256};
use std::thread;
use tauri::{AppHandle, Emitter, Manager};

/// 视为敏感/临时内容的剪贴板类型（密码管理器等），直接跳过
const SENSITIVE_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
    "net.antelle.keeweb",
];

pub fn start_watcher(app: AppHandle) {
    thread::spawn(move || {
        let ctx = match ClipboardContext::new() {
            Ok(c) => c,
            Err(e) => {
                eprintln!("clipboard context init failed: {e}");
                return;
            }
        };
        let handler = Handler { ctx, app };
        let mut watcher = match ClipboardWatcherContext::new() {
            Ok(w) => w,
            Err(e) => {
                eprintln!("clipboard watcher init failed: {e}");
                return;
            }
        };
        watcher.add_handler(handler);
        watcher.start_watch();
    });
}

struct Handler {
    ctx: ClipboardContext,
    app: AppHandle,
}

impl ClipboardHandler for Handler {
    fn on_clipboard_change(&mut self) {
        if let Err(e) = capture(&self.ctx, &self.app) {
            eprintln!("capture failed: {e}");
        }
    }
}

/// 以 PNG 字节读取剪贴板图片：
/// 1. 直接读 public.png（截图、浏览器复制都走这里）
/// 2. public.tiff 用 macOS 自带 sips 转 PNG（覆盖微信等只提供 TIFF 的应用；
///    clipboard-rs 内置的 image 解码器对部分 TIFF 变体不支持）
/// 3. 兜底 clipboard-rs 的 get_image
fn read_image_png_bytes(ctx: &ClipboardContext) -> Result<Vec<u8>, String> {
    if let Ok(bytes) = ctx.get_buffer("public.png") {
        if !bytes.is_empty() {
            return Ok(bytes);
        }
    }
    if let Ok(bytes) = ctx.get_buffer("public.tiff") {
        if !bytes.is_empty() {
            if let Ok(png) = tiff_to_png_via_sips(&bytes) {
                return Ok(png);
            }
        }
    }
    let img = ctx.get_image().map_err(|e| e.to_string())?;
    let tmp = std::env::temp_dir().join("clipstack_img.png");
    img.save_to_path(tmp.to_string_lossy().as_ref())
        .map_err(|e| e.to_string())?;
    let bytes = std::fs::read(&tmp).map_err(|e| e.to_string())?;
    let _ = std::fs::remove_file(&tmp);
    Ok(bytes)
}

#[cfg(target_os = "macos")]
fn tiff_to_png_via_sips(tiff: &[u8]) -> Result<Vec<u8>, String> {
    let src = std::env::temp_dir().join("clipstack_conv.tiff");
    let dst = std::env::temp_dir().join("clipstack_conv.png");
    std::fs::write(&src, tiff).map_err(|e| e.to_string())?;
    let out = std::process::Command::new("sips")
        .args(["-s", "format", "png"])
        .arg(&src)
        .arg("--out")
        .arg(&dst)
        .output()
        .map_err(|e| e.to_string())?;
    let _ = std::fs::remove_file(&src);
    if !out.status.success() {
        return Err(String::from_utf8_lossy(&out.stderr).into_owned());
    }
    let bytes = std::fs::read(&dst).map_err(|e| e.to_string())?;
    let _ = std::fs::remove_file(&dst);
    Ok(bytes)
}

#[cfg(not(target_os = "macos"))]
fn tiff_to_png_via_sips(_tiff: &[u8]) -> Result<Vec<u8>, String> {
    Err("unsupported".into())
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    hex_encode(&hasher.finalize())
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn now_secs() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

/// 来源 App 图标（带内存缓存，避免每次复制都做 TIFF→PNG 转换）
fn cached_icon(app: &AppHandle, bundle_id: &str) -> Option<String> {
    let state = app.state::<AppState>();
    if let Some(cached) = state.icon_cache.lock().unwrap().get(bundle_id) {
        return cached.clone();
    }
    let icon = appicon::icon_for(bundle_id);
    state
        .icon_cache
        .lock()
        .unwrap()
        .insert(bundle_id.to_string(), icon.clone());
    icon
}

/// 检测文本类型：链接 / 颜色 / 纯文本
fn classify_text(text: &str) -> &'static str {
    let t = text.trim();
    if t.starts_with("http://") || t.starts_with("https://") {
        if !t.contains(char::is_whitespace) {
            return "link";
        }
    }
    let is_color = t
        .strip_prefix('#')
        .map(|h| matches!(h.len(), 3 | 6 | 8) && h.chars().all(|c| c.is_ascii_hexdigit()))
        .unwrap_or(false);
    if is_color {
        return "color";
    }
    "text"
}

fn capture(ctx: &ClipboardContext, app: &AppHandle) -> Result<(), String> {
    let state = app.state::<AppState>();

    if state.paused.load(std::sync::atomic::Ordering::Relaxed) {
        return Ok(());
    }

    let formats = ctx.available_formats().map_err(|e| e.to_string())?;
    if formats.iter().any(|f| SENSITIVE_TYPES.contains(&f.as_str())) {
        return Ok(());
    }

    let now = now_secs();

    // 来源 = 剪贴板变化那一刻的系统前台 App（Maccy 同款方案）
    let front = appicon::frontmost_app();

    // 忽略规则：来源 App 在忽略列表中则跳过
    if let Some((bid, _)) = &front {
        let ignored: Vec<String> = {
            let conn = state.db.lock().unwrap();
            db::get_setting(&conn, "ignored_apps")
                .and_then(|v| serde_json::from_str(&v).ok())
                .unwrap_or_default()
        };
        if ignored.iter().any(|b| b == bid) {
            return Ok(());
        }
    }

    let (source_name, source_icon, source_bundle) = match front {
        Some((bid, name)) => {
            let icon = cached_icon(app, &bid);
            (Some(name), icon, Some(bid))
        }
        None => (None, None, None),
    };
    let (src_name, src_icon, src_bundle) = (
        source_name.as_deref(),
        source_icon.as_deref(),
        source_bundle.as_deref(),
    );

    // 文件优先于图片优先于文本
    if ctx.has(ContentFormat::Files) {
        let files = ctx.get_files().map_err(|e| e.to_string())?;
        if files.is_empty() {
            return Ok(());
        }
        let names: Vec<String> = files
            .iter()
            .map(|p| {
                std::path::Path::new(p)
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_else(|| p.clone())
            })
            .collect();
        let text = if names.len() == 1 {
            names[0].clone()
        } else {
            format!("{} 等 {} 个文件", names[0], names.len())
        };
        let meta = serde_json::to_string(&files).map_err(|e| e.to_string())?;
        let hash = sha256_hex(format!("file\x1f{}", files.join("\x1f")).as_bytes());
        return save(app, "file", &text, Some(&meta), None, src_name, src_icon, src_bundle, None, &hash, now);
    }

    if ctx.has(ContentFormat::Image) {
        let bytes = read_image_png_bytes(ctx)?;
        let hash = sha256_hex(&bytes);
        let orig = state.images_dir.join(format!("{}.png", &hash[..16]));
        std::fs::write(&orig, &bytes).map_err(|e| e.to_string())?;

        let img = clipboard_rs::common::RustImageData::from_bytes(&bytes)
            .map_err(|e| e.to_string())?;
        let thumb = img.thumbnail(200, 200).map_err(|e| e.to_string())?;
        let thumb_path = state.images_dir.join(format!("{}_thumb.png", &hash[..16]));
        thumb
            .save_to_path(thumb_path.to_string_lossy().as_ref())
            .map_err(|e| e.to_string())?;
        let thumb_bytes = std::fs::read(&thumb_path).map_err(|e| e.to_string())?;
        let _ = std::fs::remove_file(&thumb_path);
        let data_url = format!(
            "data:image/png;base64,{}",
            base64::engine::general_purpose::STANDARD.encode(thumb_bytes)
        );
        return save(
            app,
            "image",
            "图片",
            None,
            Some(&data_url),
            src_name,
            src_icon,
            src_bundle,
            None,
            &hash,
            now,
        );
    }

    if ctx.has(ContentFormat::Text) {
        let text = ctx.get_text().map_err(|e| e.to_string())?;
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return Ok(());
        }
        // 同时读取 HTML 表示（富文本粘贴用）
        let html = if ctx.has(ContentFormat::Html) {
            ctx.get_html().ok().filter(|h| !h.trim().is_empty())
        } else {
            None
        };
        let kind = classify_text(trimmed);
        let hash = sha256_hex(format!("{kind}\x1f{trimmed}").as_bytes());
        return save(app, kind, trimmed, None, None, src_name, src_icon, src_bundle, html.as_deref(), &hash, now);
    }

    Ok(())
}

fn save(
    app: &AppHandle,
    kind: &str,
    text: &str,
    meta: Option<&str>,
    thumb: Option<&str>,
    source: Option<&str>,
    source_icon: Option<&str>,
    source_bundle: Option<&str>,
    html: Option<&str>,
    hash: &str,
    now: i64,
) -> Result<(), String> {
    let state = app.state::<AppState>();

    // 自己写回剪贴板触发的变更，忽略（防回环）
    {
        let mut last = state.last_self_write.lock().unwrap();
        if last.as_deref() == Some(hash) {
            *last = None;
            return Ok(());
        }
    }

    let capacity: i64 = {
        let conn = state.db.lock().unwrap();
        db::upsert_clip(&conn, kind, text, meta, thumb, source, source_icon, source_bundle, html, hash, now)
            .map_err(|e| e.to_string())?;
        db::get_setting(&conn, "capacity")
            .and_then(|v| v.parse().ok())
            .unwrap_or(500)
    };

    // 超出容量时清理，同时删除对应的图片文件
    let pruned = {
        let conn = state.db.lock().unwrap();
        db::prune(&conn, capacity).map_err(|e| e.to_string())?
    };
    for h in pruned {
        let _ = std::fs::remove_file(state.images_dir.join(format!("{}.png", &h[..16.min(h.len())])));
    }

    app.emit("clipboard://updated", ()).map_err(|e| e.to_string())?;
    Ok(())
}
